/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AclModal: typeof import('./components/modals/AclModal.vue')['default']
    BandLockModal: typeof import('./components/modals/BandLockModal.vue')['default']
    DeviceTopBar: typeof import('./components/DeviceTopBar.vue')['default']
    GaugeChart: typeof import('./components/GaugeChart.vue')['default']
    GridCard: typeof import('./components/GridCard.vue')['default']
    HeaderPoem: typeof import('./components/HeaderPoem.vue')['default']
    HeaderWeather: typeof import('./components/HeaderWeather.vue')['default']
    InfoRow: typeof import('./components/InfoRow.vue')['default']
    InsecureAccessNotice: typeof import('./components/InsecureAccessNotice.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NetworkModeModal: typeof import('./components/modals/NetworkModeModal.vue')['default']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    OperationProgressModal: typeof import('./components/common/OperationProgressModal.vue')['default']
    QrModal: typeof import('./components/modals/QrModal.vue')['default']
    RingGauge: typeof import('./components/RingGauge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollingLineChart: typeof import('./components/ScrollingLineChart.vue')['default']
    ServiceStoppedNotice: typeof import('./components/ServiceStoppedNotice.vue')['default']
    StepWizard: typeof import('./components/StepWizard.vue')['default']
    ToggleRow: typeof import('./components/ToggleRow.vue')['default']
    ValueBadge: typeof import('./components/ValueBadge.vue')['default']
    VerificationToast: typeof import('./components/VerificationToast.vue')['default']
    VideoPlayer: typeof import('./components/VideoPlayer.vue')['default']
  }
}
